### ISSUE TITLE
Zoom the map

### ISSUE THREAD

**Issue by davehakkens** [hakkens/precious-plastic-spread#1]
Can we zoom in the map one more step on default?
Looks prettier in the website. I'll adjust the iframe accordingly later

**Comment by tmfrnz** [comment]
Zoom is set to fit data. So a larger iframe should result in higher initial
zoom

**Comment by davehakkens** [comment]
When I make a larger iframe I get these grey borders: 
![image](https://cloud.githubusercontent.com/assets/13672737/14230281/1c9000be-f972-11e5-9819-5055e0191c51.png)

**Comment by tmfrnz** [comment]
With the current locations for the map to load with the next zoom level the minimum iframe size must be 1006x567px

Current dimensions are 900x410px

![screen shot 2016-04-06 at 10 42 01](https://cloud.githubusercontent.com/assets/5811956/14300384/3f805cc6-fbe4-11e5-904c-06507dbb27f3.png)

**Comment by leo** [comment]
@tmfrnz The problem is that we CAN make the map higher, but we CAN NOT make it wider, since it would break out of the existing container width. What about setting [minZoom](http://leafletjs.com/reference.html#map-minzoom)?

**Comment by tmfrnz** [comment]
Of course we can set minZoom but it would result in cutting off some data points (eg New Zealand) for regular screens and even more for small screens so I would advise against it. 

Still suggest to rather make the iframe wider that is actually not limited by any existing container.

**Comment by leo** [comment]
@tmfrnz Not in terms of the code, but rather in terms of the design. Since the map isn't a background image, it needs to be on the same line as all the other stuff... :blush:

Let's say we're going to set minZoom, will people still be able to scale the map so that they can see all data points? Probably not, I assume.

**Comment by tmfrnz** [comment]
@leo yes we can set[ initial zoom and map center](http://leafletjs.com/reference.html#map-options) instead of using the [fitBounds](https://github.com/hakkens/precious-plastic-map/blob/master/js/main.js#L182) function. This will still allow zooming out. Just let me know and I can adjust this

**Comment by leo** [comment]
That sounds great!

**Comment by tmfrnz** [comment]
@leo: done. now you could increase the iframe height slightly if you like

**Comment by leo** [comment]
@tmfrnz Thank you very much! :blush:
