### ISSUE TITLE
Host map tiles on your own MapBox account

### ISSUE THREAD

**Issue by tmfrnz** [hakkens/precious-plastic-spread#4]
Also you will have to host the basemap tiles on your own mapbox account or alternative infrastructure of your preference.
https://www.mapbox.com/pricing/

Our current plan is "Standard" but current usage for this month is already 50k of 100k total (most of which is likely to come from your map)

Also you can get in touch with them and ask for non-profit discount
https://www.mapbox.com/help/nonprofit-student-plan/

**Comment by davehakkens** [comment]
thanks for the tip! Send them a mail as non profit, i’ll keep you posted

Op maandag 11 april 2016, om 09:43 heeft Timo Franz het volgende geschreven:

**Comment by tmfrnz** [comment]
using custom google maps now

**Comment by davehakkens** [comment]
that looks super neat, and it all works again. Nice Job Timo!

Op zondag 15 mei 2016, om 16:11 heeft Timo Franz het volgende geschreven:
